###
GET http://localhost:8080/api/regulation/emp

###
GET http://localhost:8080/api/regulation/emp/getRegulation2021-10-07

###
POST http://localhost:8080/api/regulation/hr/addRegulation
Content-Type: application/json

{
  "startDate": "2020-02-01",
  "endDate": "2020-02-03",
  "percentage": 50
}

###
PUT http://localhost:8080/api/regulation/hr/updateRegulation2020-02-01
Content-Type: application/json

{
  "startDate": "2020-02-01",
  "endDate": "2020-02-10",
  "percentage": 30
}

###
DELETE http://localhost:8080/api/regulation/hr/deleteRegulation2020-02-01

###
GET http://localhost:8080/api/regulationLimit/emp

###
POST http://localhost:8080/api/regulationLimit/hr/addRegulationLimit
Content-Type: application/json

{
  "regulationLimitKey": {
    "startDate": "2021-10-08",
    "cid": 2
  },
  "dailyLimit": 50
}

###
GET http://localhost:8080/api/regulationLimit/emp/getRegulationLimit/startDate2021-10-08/cid2

###
PUT http://localhost:8080/api/regulationLimit/hr/updateRegulationLimit/startDate2021-10-08/cid2
Content-Type: application/json

{
  "regulationLimitKey": {
    "startDate": "2021-10-08",
    "cid": 2
  },
  "dailyLimit": 100
}

###
DELETE http://localhost:8080/api/regulationLimit/hr/deleteRegulationLimit/startDate2021-10-08/cid2